### ISSUE TITLE
Split out front-end application into it's own module?

### ISSUE THREAD

**Issue by pudo** [spendb/spendb#15]
Currently, the complete Angular application lives in ``spendb/static/js``. This might be happier if it was split out to it's own module, so that we can use Gulp to build it, and aren't reliant on the ``flask-webassets`` asset pipeline (which I suspect will make testing that stuff harder, see #6). 

Thoughts, @milafrerichs, @mattfullerton?

**Comment by milafrerichs** [comment]
Yes I think this is a good idea. Since the Frontend is only using the API it should be easy to move it into it's own project/module. 
Will make testing and contributions easier. 
so :+1: on this

**Comment by mattfullerton** [comment]
:+1:

**Comment by holgerd77** [comment]
Moved to own repo spendb/spendb.ui
